"""The documented update-recovery commands, defined once (CF-22.02, ADR 0053).

`docs/user-guide/updates.md` and `migration.md` document these exact commands.
`tests/test_update_recovery.py` runs them against real repositories in every
state an update can leave behind, `tests/test_e2e_installed_cutover.py` runs
them against a project generated by the installed console, and
`tests/test_user_guide_recipes.py` asserts the guide still says them -- so the
guide, the evidence, and the drift guard share one source.

Nothing here imports `create_forge`, so the installed-console suites can use it
without importing the source tree. `tests/test_update_recovery.py` asserts these
strings equal `create_forge.update`'s own constants, which is what keeps the
CLI's printed guidance from drifting away from what the guide documents.
"""

from __future__ import annotations

import shlex

RESTORE_COMMAND = "git restore --source=HEAD --staged --worktree ."
CLEAN_PREVIEW_COMMAND = "git clean -nd"
CLEAN_COMMAND = "git clean -fd"

# What published `create-forge 0.4.0` prints. It restores the worktree from the
# *index*, so it does nothing for an update that is already staged (or a rename
# interrupted after `git mv`). The guide names it only to tell 0.4.0 users not
# to rely on it; it must never appear as a recipe.
LEGACY_0_4_0_HINT = "git restore . && git clean -fd"

RESTORE_ARGV = tuple(shlex.split(RESTORE_COMMAND))
CLEAN_PREVIEW_ARGV = tuple(shlex.split(CLEAN_PREVIEW_COMMAND))
CLEAN_ARGV = tuple(shlex.split(CLEAN_COMMAND))
